name: flutter_dent_lab
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^6.5.8
  google_fonts: ^4.0.3
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.1
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/



